#!/usr/bin/env python3
"""Export the exact active-site probability channel used by a SiteWeaver cache.

The exported values are residue-aligned float32 values copied from the cache.
They are not regenerated by this script, so a collaborator can use exactly
the same active-site input while changing the PRS calculation.
"""

from __future__ import annotations

import argparse
import csv
import gzip
import hashlib
import json
from pathlib import Path

from siteweaver.cache.r0_cache_io import load_all_cached_samples


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def _portable(value):
    """Remove workstation-specific prefixes from copied provenance metadata."""
    if isinstance(value, dict):
        return {key: _portable(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_portable(item) for item in value]
    if isinstance(value, str):
        marker = "/projects/"
        if marker in value:
            return value[value.index(marker) + 1:]
        marker = "/tmp/"
        if marker in value:
            return value[value.index(marker) + 1:]
        if value.startswith("/"):
            return Path(value).name
    return value


def _split_map(path: Path | None) -> dict[str, str]:
    if path is None:
        return {}
    with path.open(newline="") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames != ["complex_id", "split"]:
            raise ValueError(f"Expected exactly complex_id,split in {path}")
        result: dict[str, set[str]] = {}
        for row in reader:
            key = str(row["complex_id"]).strip().upper()
            result.setdefault(key, set()).add(str(row["split"]).strip().lower())
        return {key: ";".join(sorted(values)) for key, values in result.items()}


def export(cache_dir: Path, output: Path, split_file: Path | None = None) -> dict:
    manifest_path = cache_dir / "manifest.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(manifest_path)
    cache_manifest = json.loads(manifest_path.read_text())
    samples = load_all_cached_samples(cache_dir)
    splits = _split_map(split_file)

    output.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "complex_id",
        "pdb_id",
        "split",
        "residue_index",
        "chain_id",
        "residue_number",
        "insertion_code",
        "residue_name",
        "active_site_probability",
    ]
    n_rows = 0
    n_samples = 0
    with gzip.open(output, "wt", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for sample in sorted(samples, key=lambda item: str(item.get("complex_id", "")).upper()):
            complex_id = str(sample.get("complex_id", "")).strip()
            key = complex_id.upper()
            probabilities = sample.get("active_site_probability")
            residue_meta = list(sample.get("residue_meta", []))
            if probabilities is None:
                raise ValueError(f"Missing active_site_probability for {complex_id}")
            probabilities = probabilities.detach().cpu().numpy().reshape(-1)
            if len(probabilities) != len(residue_meta):
                raise ValueError(
                    f"Residue/probability length mismatch for {complex_id}: "
                    f"{len(residue_meta)} != {len(probabilities)}"
                )
            for residue_index, (meta, probability) in enumerate(zip(residue_meta, probabilities)):
                writer.writerow({
                    "complex_id": complex_id,
                    "pdb_id": str(sample.get("pdb_id", "")),
                    "split": splits.get(key, str(sample.get("split", ""))),
                    "residue_index": residue_index,
                    "chain_id": meta.get("chain_id", ""),
                    "residue_number": meta.get("res_num", ""),
                    "insertion_code": meta.get("ins_code", ""),
                    "residue_name": meta.get("res_name", ""),
                    "active_site_probability": f"{float(probability):.9g}",
                })
                n_rows += 1
            n_samples += 1

    metadata = {
        "file": output.name,
        "format": "gzip-compressed CSV",
        "columns": fields,
        "num_samples": n_samples,
        "num_residue_rows": n_rows,
        "active_probability_semantics": "copied_exactly_from_cache; see source_cache_manifest",
        "source_cache": str(cache_dir),
        "source_cache_manifest_sha256": _sha256(manifest_path),
        "source_cache_manifest": _portable(cache_manifest),
        "split_file": str(split_file) if split_file else None,
        "split_file_sha256": _sha256(split_file) if split_file else None,
    }
    metadata_path = output.with_suffix(output.suffix + ".json")
    metadata_path.write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n")
    return {"output": str(output), "metadata": str(metadata_path), **metadata}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cache-dir", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True, help="Output .csv.gz path")
    parser.add_argument("--split-file", type=Path, default=None)
    args = parser.parse_args()
    print(json.dumps(export(args.cache_dir, args.output, args.split_file), indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
